# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('runtime', models.FloatField(max_length=10000)),
                ('metric3', models.FloatField(max_length=10000)),
                ('metric2', models.FloatField(max_length=10000)),
                ('n_clf', models.FloatField(max_length=10000, null=True)),
                ('acc_over_time', models.FloatField(max_length=10000, null=True)),
                ('message', models.CharField(default='Not Provided', max_length=10000)),
            ],
        ),
    ]
