# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-18 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='metric2',
            new_name='acc',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='metric3',
            new_name='acc_clf',
        ),
    ]
