# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-13 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180525_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='message',
            field=models.CharField(default='Not Provided', max_length=10000),
        ),
    ]
