# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-06 18:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_score_r2'),
    ]

    operations = [
        migrations.AddField(
            model_name='score_r2',
            name='bucket',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=2), default=0, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score_r2',
            name='metric',
            field=models.FloatField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='score_r2',
            name='ref_acc',
            field=models.FloatField(max_length=10000, null=True),
        ),
    ]
