# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-07 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181107_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_r2_detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('runtime', models.FloatField(max_length=10000)),
                ('map_over_time', models.FloatField(max_length=10000)),
                ('map_of_processed', models.FloatField(max_length=10000)),
                ('message', models.CharField(default='Not Provided', max_length=10000)),
            ],
        ),
    ]
