# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_score_r2_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='score_r2_detection',
            name='metric',
            field=models.FloatField(max_length=10000, null=True),
        ),
    ]
