# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tfile2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfile1',
            name='fn',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tfile2',
            name='fn',
            field=models.CharField(max_length=1000),
        ),
    ]
