# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blogpage_blogpagerelatedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Footer Bio')),
                ('content', models.CharField(max_length=3000, verbose_name='Footer Content')),
            ],
        ),
    ]
