# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Footer Bio')),
                ('image_link', models.CharField(max_length=2000, verbose_name='image link')),
            ],
        ),
    ]
