# Generated by Django 2.0.9 on 2018-10-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='redirect_link',
            field=models.CharField(blank=True, max_length=2000, verbose_name='image link'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='redirect_link',
            field=models.CharField(blank=True, max_length=2000, verbose_name='image link'),
        ),
    ]
